# Generated by Django 3.2 on 2023-12-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caketype', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
